language: node_js
node_js:
  - "4"
  - "5"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install -g bower
  - npm install -g karma
  - npm install -g grunt
  - npm install phantomjs
  - npm install
  - bower install
script:
  - npm test
